version: '3.5'

services:   
    
  proxy:
    image: radiofisik/proxy
    restart: always
    ports:
      - 80:80
    extra_hosts:
      - "debughost: ${DEBUGGER_HOST}"

  elastic:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
      restart: always
      environment:
        - ES_JAVA_OPTS=-Xms4g -Xmx4g
        - cluster.name=elasticl
      ports:
        - 19202:9200
        - 19302:9300
      volumes:
        - elastic_data_l:/usr/share/elasticsearch/data
        - elastic_log_l:/usr/share/elasticsearch/logs

  kibana:
      image: docker.elastic.co/kibana/kibana:6.8.0
      restart: always
      ports:
      - 5602:5601
      environment:
        ELASTICSEARCH_URL: http://elastic:9200
      depends_on:
        - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.0
    restart: always
    ports:
      - 5046:5046
      - 5000:5000
    volumes:
      - ./Configs/Logstash/pipeline:/usr/share/logstash/config/pipeline
      - ./Configs/Logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
    environment:
      xpack.monitoring.elasticsearch.url: http://elastic:9200
    depends_on:
      - elastic

  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 8080:15672
      - 5672:5672
    volumes:
      - ./Configs/Rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  postgres:
    image: postgres:11.2-alpine
    restart: always
    shm_size: 256M
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: appbd
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
    - ./Configs/Postgres/postgres.conf:/etc/postgresql/postgresql.conf
    - postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432

  app:
    image: radiofisik/app
    restart: always
    ports:
      - 8081:80
    environment:
      Connections:ElasticSearchConnectionString: http://elastic:9200
      Connections:RabbitConnectionString: amqp://rabbit

volumes:
  elastic_data_l: {}
  elastic_log_l: {}
  postgres_data: {}
