version: '3.5'

services:       
  proxy:
    build:
        context: ./Proxy
        dockerfile: Dockerfile
  app:
    build:
        context: ./App
        dockerfile: /App/App/Dockerfile

  auth:
    build:
        context: ./App
        dockerfile: /Auth/AuthServer/Dockerfile

  front:
      build:
        context: './Front'
        dockerfile: 'Dockerfile'